spring:
  datasource:
    username: admin
    password: Nag15188
    url: jdbc:mysql://mysql.cjyk62o4exjc.ap-south-1.rds.amazonaws.com:3306/BrinkerIncUser
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
springdoc:
  swagger-ui:
   path: /swagger-ui.html